---
output: 
  html_document:
    theme: NULL
---

```{r setup, include = FALSE}
library(tidyverse)
library(DT)
library(readxl)
library(here)


day1a <- read_excel(here("themes", "Program With Abstracts.xlsx"), 
                  sheet = "Day 1", skip = 1) %>% 
  rename(Title = `...4`) %>% 
  mutate(` ` = case_when(
    is.na(Abstract) ~ "",
    TRUE ~ '&oplus;'
  )) %>% 
  mutate(Day = "Tue") %>% 
  select(` `, Day, everything()) %>% 
  mutate(Start = paste0(lubridate::hour(Start), ":", 
                        sprintf('%.2d', lubridate::minute(Start)))) %>% 
  select(-Start, -Day, -Title)


day2a <- read_excel(here("themes", "Program With Abstracts.xlsx"), 
                  sheet = "Day 2", skip = 1) %>% 
  rename(Title = `...4`, 
         Session = `...2`)  %>% 
  mutate(` ` = case_when(
    is.na(Abstract) ~ "",
    TRUE ~ '&oplus;'
  )) %>% 
  mutate(Day = "Wed") %>% 
  select(` `, Day, everything()) %>% 
  rename(Speaker = Description) %>% 
  mutate(Start = paste0(lubridate::hour(Start), ":", 
                        sprintf('%.2d', lubridate::minute(Start)))) %>% 
  select(-Start, -Day, -Title)

day1b <- read_excel(here("themes", "Final Program 20190926.xlsx"), 
                   sheet = "Day 1", skip = 1) %>% 
  rename(Title = `...5`) %>% 
  select(-Finish, -Minutes) %>% 
  mutate(Time = Start) %>% 
  mutate(Start = paste0(lubridate::hour(Start), ":", 
                        sprintf('%.2d', lubridate::minute(Start)))) %>% 
  mutate(Day = "Tue")

day2b <- read_excel(here("themes", "Final Program 20190926.xlsx"), 
                   sheet = "Day 2", skip = 1) %>% 
  rename(Session = `...3`, Title = `...5`,
         Speaker = Description) %>% 
  select(-Finish, -Minutes) %>% 
  mutate(Time = Start) %>% 
  mutate(Start = paste0(lubridate::hour(Start), ":", 
                        sprintf('%.2d', lubridate::minute(Start)))) %>% 
  mutate(Day = "Wed")

day12a <- rbind(day1a, day2a) %>% 
  mutate(Join = case_when(
    !is.na(Speaker) ~ Speaker,
    is.na(Speaker) ~ Session
  )) %>% 
  select(-Session)

day12b <- rbind(day1b, day2b) %>% 
  mutate(Join = case_when(
    !is.na(Speaker) ~ Speaker,
    is.na(Speaker) ~ Session
  ))

dat <- left_join(day12b, day12a, by = c("Speaker", "Join")) %>% 
  arrange(Day, Time) %>% 
  select(` `, Day, Start, Session, Speaker, Title, Abstract) %>% 
  distinct() 
remove_dat <- dat %>% 
  filter(!is.na(Speaker) & Speaker=="Farzana Jahan") %>% 
  filter((grepl("Bayesian Empirical Likelihood", Title) & 
         grepl("Analysis of spatial patterns", Abstract)) |
        (grepl("Augmenting Disease maps", Title) & 
         grepl("Bayesian empirical likelihood", Abstract))
  )
dat2 <- setdiff(dat, remove_dat)

```


```{r dt, include = FALSE}
dt <- datatable(dat2,
  elementId = "programme", 
  escape = -2,,
  options = list(
    columnDefs = list(
      list(visible = FALSE, targets = c(0, 7)),
      list(orderable = FALSE, className = 'details-control', targets = 1)
    ),
    buttons = c('csv', 'excel', 'print'),
    dom = 'Bfrtip',
    paging = FALSE
  ),
  callback = JS("
  table.column(1).nodes().to$().css({cursor: 'pointer'});
  var format = function(d) {
    return '<div style=\"background-color:#eee; padding: .5em;\"> <b>Abstract</b>: ' +
            d[7] 
            '</div>';
  };
  table.on('click', 'td.details-control', function() {
    var td = $(this), row = table.row(td.closest('tr'));
    if (row.child.isShown()) {
      row.child.hide();
      td.html('&oplus;');
    } else {
      row.child(format(row.data())).show();
      td.html('&CircleMinus;');
    }
  });"
  ),
  extensions = 'Buttons'
  )
dt

saveWidget(dt, here("themes", 'programmeDT.html'))


```


